version: '3'

services:
  blog-sql:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - blog-sql-data:/var/opt/mssql/data
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - blognet

    
  blog-api:
    restart: unless-stopped
    build: .
    environment:
      - ConnectionStrings:BlogApi=Server=blog-sql,1433;Database=BlogApi;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 44396:80
    networks:
      - blognet

volumes:
  blog-sql-data:
      
networks:
  blognet:
    driver: bridge